In [1]:
import numpy as np

In [6]:
#create 2D array
twoDim=np.array([[1,2,3],[4,5,6]])
print(twoDim)
threeDim=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(threeDim)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#create an array with a range (start,stop,step)
np.arrange(1,11,2)