In [42]:
import numpy as np

In [43]:
#create 2D array
twoDim=np.array([[1,2,3],[4,5,6]])
print(twoDim)
threeDim=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(threeDim)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
#create an array with a range (start,stop,step)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [45]:
# arange and resize
# note make sure row*column=no of items
new_shape=np.arange(1,13).reshape(2,6)
print(new_shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [46]:
# and array with ones and zeros
np.ones((3,4))
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.random.random((3,4))

array([[0.22337226, 0.29402182, 0.77838221, 0.92106747],
       [0.2282264 , 0.36605453, 0.4870155 , 0.49785651],
       [0.20876685, 0.03252658, 0.39347957, 0.72004723]])

In [48]:
#np.linespace(Lower limit, Upper limit, No of elements to add)
#It creates elments such that gap between two elements is same
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [49]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Array Attributes**

In [50]:
a1=np.array(10) # Vector
a2=np.arange(8).reshape(2,4) # Matrix
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #Tensor

In [51]:
# ndim no of dimensions
a1.ndim
a2.ndim
a3.ndim

3

In [52]:
# Shape
a2.shape
a3.shape # (2,2,3) means (no of diminsions,rows,columns)


(2, 2, 3)

In [53]:
# Size (no of elements)
a3.size
a2.size

8

In [54]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


### **Changing Datatype**

In [55]:
a3.astype(np.int32)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

## **Array Operations**

In [56]:
arr1=np.arange(12,24).reshape(3,4)

In [57]:
# Scaler operations
print(arr1+2)
print(arr1*2)
print(arr1-2)

[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [58]:
# arithmatic operators
arr1 ** 2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [59]:
# relational operators
arr1>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
# max/min/sum/product
print(np.max(arr1))
print(np.min(arr1))
# row->1 column->0
print(np.min(arr1,axis=1))
print(np.sum(arr1))
print(np.prod(arr1))

23
12
[12 16 20]
210
647647525324800


In [61]:
# max/min/sum/prod
# 0-> col 1->row
np.prod(arr1,axis=1)
np.prod(arr1,axis=0)
np.prod(arr1)

np.int64(647647525324800)

In [62]:
print(np.median(arr1))
print(np.mean(arr1))
print(np.std(arr1))

17.5
17.5
3.452052529534663


In [63]:
np.sin(arr1)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

**DOT PRODUCT**

In [64]:
m1=np.arange(1,13).reshape(3,4)
m2=np.arange(1,13).reshape(4,3)
np.dot(m1,m2)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [65]:
np.exp(arr1)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [66]:
np.round(np.random.random((3,3))*100)

array([[87., 76., 21.],
       [50., 15., 14.],
       [50., 27., 50.]])

**INDEXING AND SLICING**

In [67]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)


In [68]:
#last elment for 1D array
a1[-1]

np.int64(9)

In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
# indexing and element in numpy
# [row,column]
a2[0,1]

np.int64(1)

In [71]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
print(a3[1,0,1])
print(a3[0,0,0])
print(a3[1,1,0])

10
0
12


In [73]:
a1[2:6]

array([2, 3, 4, 5])

In [74]:
#2D
print(a2[0,:])
print(a2[:,0])

[0 1 2 3]
[0 4 8]


In [75]:
a2[::2,::3]
# required rows are all so first :
#then skip one row in between :2
#then skip two columns hence :3

array([[ 0,  3],
       [ 8, 11]])

In [76]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [77]:
a2[:2:1,1::1]

array([[1, 2, 3],
       [5, 6, 7]])

In [78]:
# 3D
a3[1]
a3[0,1,:]
a3[1,:,1]
a3[2,1::,1::]
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### **ITERTATING**

In [79]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [80]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [81]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## **RESHAPING**

In [84]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [87]:
a3.ravel()
#converts to 1-D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## **STACKING**

In [88]:
#horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [89]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## **SPLITTING**

In [91]:
# horizontal splitting
a4=np.arange(16).reshape(4,4)
np.hsplit(a4,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [93]:
np.vsplit(a4,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]